#cloud-config
# vim: syntax=yaml

user: cloud
ssh_pwauth: True
chpasswd:
    list: |
        root:contrail123
        cloud:contrail123
    expire: False

package_update: true
package_upgrade: true
package_reboot_if_required: false

packages:
  - git
  - tig
  - subversion
  - ranger
  - oping
  - bpython
  - vim
  - traceroute
  - htop
  - mosh
  - tmux
  - screen
  - jq
  - crudini
  - make
  - libpq-dev  # rally

final_message: "!!! Devstack booted !!! (cloudinit runs in $UPTIME seconds)"

output: {all: '| tee -a /var/log/cloud-init-output.log'}

runcmd:
  - [ sh, -xc, "su cloud -c 'cd && git clone https://github.com/rasta-rocket/dotfiles.git'" ]
  - [ sh, -xc, "su cloud -c 'cd && cd dotfiles && make install'" ]
    # - [ sh, -xc, "su cloud -c 'cd && git clone https://github.com/nojhan/liquidprompt.git'" ]
    # - [ sh, -xc, "su cloud -c 'echo source ~/liquidprompt/liquidprompt >> /home/cloud/.bashrc'" ]
  - [ sh, -xc, "su cloud -c 'git config --global http.sslVerify false'"]
  - [ sh, -xc, "su cloud -c 'bash /opt/build.sh'" ]

write_files:
-   content: |
        #!/usr/bin/env bash
        tmux new-session -s opencontrail -n shell -d
        tmux new-window -t opencontrail:1 -n contrail
        tmux new-window -t opencontrail:2 -n stack
        tmux send-keys -t opencontrail:2 'cd ~/ && git clone https://github.com/openstack-dev/devstack && git clone https://github.com/Juniper/contrail-installer.git' C-m
    path: /opt/build.sh
    permissions: 0775
-   content: |
     [[local|localrc]]
        SERVICE_TOKEN=azertytoken
        ADMIN_PASSWORD=contrail123
        MYSQL_PASSWORD=stackdb
        RABBIT_PASSWORD=stackqueue
        SERVICE_PASSWORD=$ADMIN_PASSWORD
        LOGFILE=$DEST/logs/stack.sh.log
        LOGDAYS=2
        SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
        SWIFT_REPLICAS=1
        SWIFT_DATA_DIR=$DEST/data

        REQUIREMENTS_REPO="https://github.com/rasta-rocket/requirements.git"
        REQUIREMENTS_BRANCH="cloudwatt-stable/mitaka"

        #Enable heat services
        enable_service h-eng h-api h-api-cfn h-api-cw

        # Download Fedora image
        IMAGE_URLS="https://download.fedoraproject.org/pub/fedora/linux/releases/24/CloudImages/x86_64/images/Fedora-Cloud-Base-24-1.2.x86_64.qcow2"

        enable_plugin contrail https://github.com/zioc/contrail-devstack-plugin.git
        CONTRAIL_REPO=https://github.com/Juniper/contrail-vnc.git
        CONTRAIL_BRANCH=master
        Q_PLUGIN_CLASS=neutron_plugin_contrail.plugins.opencontrail.contrail_plugin.NeutronPluginContrailCoreV2
        disable_service ui-jobs ui-webs

        enable_plugin networking-bgpvpn https://github.com/openstack/networking-bgpvpn.git stable/mitaka
        NETWORKING_BGPVPN_DRIVER="BGPVPN:OpenContrail:networking_bgpvpn.neutron.services.service_drivers.opencontrail.opencontrail.OpenContrailBGPVPNDriver:default"

        SCONS_JOBS=1 #$(lscpu -p | grep -cve '^#')
     [[post-config|$NEUTRON_CONF]]
        [DEFAULT]
        #service_plugins = neutron_plugin_contrail.plugins.opencontrail.loadbalancer.plugin.LoadBalancerPlugin
        [quotas]
        quota_driver = neutron_plugin_contrail.plugins.opencontrail.quota.driver.QuotaDriver
     [[post-config|$NOVA_CONF]]
        [libvirt]
        vif_driver = nova_contrail_vif.contrailvif.VRouterVIFDriver
        virt_type = qemu   
    path: /opt/local.conf
    permissions: 0664
